# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = plasma-workspace

HEADERS = \
   $$PWD/applets/appmenu/lib/appmenuapplet.h \
   $$PWD/applets/appmenu/plugin/appmenumodel.h \
   $$PWD/applets/appmenu/plugin/appmenuplugin.h \
   $$PWD/applets/calendar/calendarapplet.h \
   $$PWD/applets/digital-clock/plugin/clipboardmenu.h \
   $$PWD/applets/digital-clock/plugin/digitalclockplugin.h \
   $$PWD/applets/digital-clock/plugin/timezonedata.h \
   $$PWD/applets/digital-clock/plugin/timezonemodel.h \
   $$PWD/applets/digital-clock/plugin/timezonesi18n.h \
   $$PWD/applets/icon/iconapplet.h \
   $$PWD/applets/kicker/plugin/abstractentry.h \
   $$PWD/applets/kicker/plugin/abstractmodel.h \
   $$PWD/applets/kicker/plugin/actionlist.h \
   $$PWD/applets/kicker/plugin/appentry.h \
   $$PWD/applets/kicker/plugin/appsmodel.h \
   $$PWD/applets/kicker/plugin/computermodel.h \
   $$PWD/applets/kicker/plugin/contactentry.h \
   $$PWD/applets/kicker/plugin/containmentinterface.h \
   $$PWD/applets/kicker/plugin/dashboardwindow.h \
   $$PWD/applets/kicker/plugin/draghelper.h \
   $$PWD/applets/kicker/plugin/fileentry.h \
   $$PWD/applets/kicker/plugin/forwardingmodel.h \
   $$PWD/applets/kicker/plugin/funnelmodel.h \
   $$PWD/applets/kicker/plugin/kastatsfavoritesmodel.h \
   $$PWD/applets/kicker/plugin/kickerplugin.h \
   $$PWD/applets/kicker/plugin/menuentryeditor.h \
   $$PWD/applets/kicker/plugin/placeholdermodel.h \
   $$PWD/applets/kicker/plugin/processrunner.h \
   $$PWD/applets/kicker/plugin/recentcontactsmodel.h \
   $$PWD/applets/kicker/plugin/recentusagemodel.h \
   $$PWD/applets/kicker/plugin/rootmodel.h \
   $$PWD/applets/kicker/plugin/runnermatchesmodel.h \
   $$PWD/applets/kicker/plugin/runnermodel.h \
   $$PWD/applets/kicker/plugin/simplefavoritesmodel.h \
   $$PWD/applets/kicker/plugin/submenu.h \
   $$PWD/applets/kicker/plugin/systementry.h \
   $$PWD/applets/kicker/plugin/systemmodel.h \
   $$PWD/applets/kicker/plugin/systemsettings.h \
   $$PWD/applets/kicker/plugin/wheelinterceptor.h \
   $$PWD/applets/kicker/plugin/windowsystem.h \
   $$PWD/applets/notifications/filemenu.h \
   $$PWD/applets/notifications/globalshortcuts.h \
   $$PWD/applets/notifications/notificationapplet.h \
   $$PWD/applets/notifications/thumbnailer.h \
   $$PWD/applets/panelspacer/plugin/panelspacer.h \
   $$PWD/applets/systemmonitor/systemmonitor/systemmonitor.h \
   $$PWD/applets/systemtray/container/systemtraycontainer.h \
   $$PWD/applets/systemtray/tests/statusnotifier/pumpjob.h \
   $$PWD/applets/systemtray/tests/statusnotifier/statusnotifiertest.h \
   $$PWD/applets/systemtray/sortedsystemtraymodel.h \
   $$PWD/applets/systemtray/systemtray.h \
   $$PWD/applets/systemtray/systemtraymodel.h \
   $$PWD/appmenu/appmenu.h \
   $$PWD/appmenu/appmenu_dbus.h \
   $$PWD/appmenu/kdbusimporter.h \
   $$PWD/appmenu/menuimporter.h \
   $$PWD/appmenu/verticalmenu.h \
   $$PWD/components/containmentlayoutmanager/abstractlayoutmanager.h \
   $$PWD/components/containmentlayoutmanager/appletcontainer.h \
   $$PWD/components/containmentlayoutmanager/appletslayout.h \
   $$PWD/components/containmentlayoutmanager/configoverlay.h \
   $$PWD/components/containmentlayoutmanager/containmentlayoutmanagerplugin.h \
   $$PWD/components/containmentlayoutmanager/gridlayoutmanager.h \
   $$PWD/components/containmentlayoutmanager/itemcontainer.h \
   $$PWD/components/containmentlayoutmanager/resizehandle.h \
   $$PWD/components/keyboardlayout/keyboardlayout.h \
   $$PWD/components/keyboardlayout/keyboardlayoutplugin.h \
   $$PWD/components/sessionsprivate/sessionsmodel.h \
   $$PWD/components/sessionsprivate/sessionsprivateplugin.h \
   $$PWD/components/shellprivate/interactiveconsole/interactiveconsole.h \
   $$PWD/components/shellprivate/wallpaperplugin/wallpaperplugin.h \
   $$PWD/components/shellprivate/widgetexplorer/kcategorizeditemsviewmodels_p.h \
   $$PWD/components/shellprivate/widgetexplorer/openwidgetassistant_p.h \
   $$PWD/components/shellprivate/widgetexplorer/plasmaappletitemmodel_p.h \
   $$PWD/components/shellprivate/widgetexplorer/widgetexplorer.h \
   $$PWD/components/shellprivate/shellprivateplugin.h \
   $$PWD/containmentactions/applauncher/launch.h \
   $$PWD/containmentactions/contextmenu/menu.h \
   $$PWD/containmentactions/paste/paste.h \
   $$PWD/containmentactions/switchactivity/switch.h \
   $$PWD/containmentactions/switchdesktop/desktop.h \
   $$PWD/containmentactions/switchwindow/switch.h \
   $$PWD/dataengines/activities/ActivityData.h \
   $$PWD/dataengines/activities/activityengine.h \
   $$PWD/dataengines/activities/activityjob.h \
   $$PWD/dataengines/activities/activityservice.h \
   $$PWD/dataengines/applicationjobs/jobaction.h \
   $$PWD/dataengines/applicationjobs/jobcontrol.h \
   $$PWD/dataengines/applicationjobs/kuiserverengine.h \
   $$PWD/dataengines/apps/appjob.h \
   $$PWD/dataengines/apps/appsengine.h \
   $$PWD/dataengines/apps/appservice.h \
   $$PWD/dataengines/apps/appsource.h \
   $$PWD/dataengines/devicenotifications/devicenotificationsengine.h \
   $$PWD/dataengines/devicenotifications/ksolidnotify.h \
   $$PWD/dataengines/dict/dictengine.h \
   $$PWD/dataengines/executable/executable.h \
   $$PWD/dataengines/favicons/faviconprovider.h \
   $$PWD/dataengines/favicons/favicons.h \
   $$PWD/dataengines/filebrowser/filebrowserengine.h \
   $$PWD/dataengines/geolocation/geolocation.h \
   $$PWD/dataengines/geolocation/geolocationprovider.h \
   $$PWD/dataengines/geolocation/location_gps.h \
   $$PWD/dataengines/geolocation/location_ip.h \
   $$PWD/dataengines/hotplug/deviceaction.h \
   $$PWD/dataengines/hotplug/deviceserviceaction.h \
   $$PWD/dataengines/hotplug/hotplugengine.h \
   $$PWD/dataengines/hotplug/hotplugjob.h \
   $$PWD/dataengines/hotplug/hotplugservice.h \
   $$PWD/dataengines/keystate/keyservice.h \
   $$PWD/dataengines/keystate/keystate.h \
   $$PWD/dataengines/mouse/cursornotificationhandler.h \
   $$PWD/dataengines/mouse/mouseengine.h \
   $$PWD/dataengines/mpris2/mpris2engine.h \
   $$PWD/dataengines/mpris2/multiplexedservice.h \
   $$PWD/dataengines/mpris2/multiplexer.h \
   $$PWD/dataengines/mpris2/playeractionjob.h \
   $$PWD/dataengines/mpris2/playercontainer.h \
   $$PWD/dataengines/mpris2/playercontrol.h \
   $$PWD/dataengines/notifications/notificationaction.h \
   $$PWD/dataengines/notifications/notificationsengine.h \
   $$PWD/dataengines/notifications/notificationservice.h \
   $$PWD/dataengines/packagekit/packagekitengine.h \
   $$PWD/dataengines/packagekit/packagekitjob.h \
   $$PWD/dataengines/packagekit/packagekitservice.h \
   $$PWD/dataengines/places/jobs.h \
   $$PWD/dataengines/places/modeljob.h \
   $$PWD/dataengines/places/placesengine.h \
   $$PWD/dataengines/places/placeservice.h \
   $$PWD/dataengines/places/placesproxymodel.h \
   $$PWD/dataengines/places/setupdevicejob.h \
   $$PWD/dataengines/powermanagement/powermanagementengine.h \
   $$PWD/dataengines/powermanagement/powermanagementjob.h \
   $$PWD/dataengines/powermanagement/powermanagementservice.h \
   $$PWD/dataengines/soliddevice/devicesignalmapmanager.h \
   $$PWD/dataengines/soliddevice/devicesignalmapper.h \
   $$PWD/dataengines/soliddevice/hddtemp.h \
   $$PWD/dataengines/soliddevice/soliddeviceengine.h \
   $$PWD/dataengines/soliddevice/soliddevicejob.h \
   $$PWD/dataengines/soliddevice/soliddeviceservice.h \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritem_engine.h \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemjob.h \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemservice.h \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemsource.h \
   $$PWD/dataengines/statusnotifieritem/systemtraytypes.h \
   $$PWD/dataengines/systemmonitor/sensorclient.h \
   $$PWD/dataengines/systemmonitor/systemmonitor.h \
   $$PWD/dataengines/time/solarsystem.h \
   $$PWD/dataengines/time/timeengine.h \
   $$PWD/dataengines/time/timesource.h \
   $$PWD/dataengines/weather/ions/bbcukmet/ion_bbcukmet.h \
   $$PWD/dataengines/weather/ions/envcan/ion_envcan.h \
   $$PWD/dataengines/weather/ions/noaa/ion_noaa.h \
   $$PWD/dataengines/weather/ions/wetter.com/ion_wettercom.h \
   $$PWD/dataengines/weather/ions/ion.h \
   $$PWD/dataengines/weather/weatherengine.h \
   $$PWD/freespacenotifier/freespacenotifier.h \
   $$PWD/freespacenotifier/module.h \
   $$PWD/gmenu-dbusmenu-proxy/actions.h \
   $$PWD/gmenu-dbusmenu-proxy/gdbusmenutypes_p.h \
   $$PWD/gmenu-dbusmenu-proxy/icons.h \
   $$PWD/gmenu-dbusmenu-proxy/menu.h \
   $$PWD/gmenu-dbusmenu-proxy/menuproxy.h \
   $$PWD/gmenu-dbusmenu-proxy/utils.h \
   $$PWD/gmenu-dbusmenu-proxy/window.h \
   $$PWD/kcms/colors/editor/previewwidget.h \
   $$PWD/kcms/colors/editor/scmeditorcolors.h \
   $$PWD/kcms/colors/editor/scmeditordialog.h \
   $$PWD/kcms/colors/editor/scmeditoreffects.h \
   $$PWD/kcms/colors/editor/scmeditoroptions.h \
   $$PWD/kcms/colors/editor/setpreviewwidget.h \
   $$PWD/kcms/colors/colors.h \
   $$PWD/kcms/colors/colorsdata.h \
   $$PWD/kcms/colors/colorsmodel.h \
   $$PWD/kcms/colors/filterproxymodel.h \
   $$PWD/kcms/cursortheme/xcursor/cursortheme.h \
   $$PWD/kcms/cursortheme/xcursor/previewwidget.h \
   $$PWD/kcms/cursortheme/xcursor/sortproxymodel.h \
   $$PWD/kcms/cursortheme/xcursor/thememodel.h \
   $$PWD/kcms/cursortheme/xcursor/xcursortheme.h \
   $$PWD/kcms/cursortheme/cursorthemedata.h \
   $$PWD/kcms/cursortheme/kcmcursortheme.h \
   $$PWD/kcms/desktoptheme/desktopthemedata.h \
   $$PWD/kcms/desktoptheme/filterproxymodel.h \
   $$PWD/kcms/desktoptheme/kcm.h \
   $$PWD/kcms/desktoptheme/themesmodel.h \
   $$PWD/kcms/feedback/feedback.h \
   $$PWD/kcms/fonts/fonts.h \
   $$PWD/kcms/fonts/fontsaasettings.h \
   $$PWD/kcms/fonts/fontsdata.h \
   $$PWD/kcms/fonts/kxftconfig.h \
   $$PWD/kcms/fonts/previewimageprovider.h \
   $$PWD/kcms/fonts/previewrenderengine.h \
   $$PWD/kcms/icons/iconsdata.h \
   $$PWD/kcms/icons/iconsizecategorymodel.h \
   $$PWD/kcms/icons/iconsmodel.h \
   $$PWD/kcms/icons/iconssettings.h \
   $$PWD/kcms/icons/main.h \
   $$PWD/kcms/kfontinst/apps/CreateParent.h \
   $$PWD/kcms/kfontinst/apps/Installer.h \
   $$PWD/kcms/kfontinst/apps/Printer.h \
   $$PWD/kcms/kfontinst/apps/Viewer.h \
   $$PWD/kcms/kfontinst/dbus/FcConfig.h \
   $$PWD/kcms/kfontinst/dbus/Folder.h \
   $$PWD/kcms/kfontinst/dbus/FontInst.h \
   $$PWD/kcms/kfontinst/dbus/FontinstIface.h \
   $$PWD/kcms/kfontinst/dbus/Helper.h \
   $$PWD/kcms/kfontinst/dbus/Utils.h \
   $$PWD/kcms/kfontinst/kcmfontinst/ActionLabel.h \
   $$PWD/kcms/kfontinst/kcmfontinst/DuplicatesDialog.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FcQuery.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FontFilter.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FontFilterProxyStyle.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FontInstInterface.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FontList.h \
   $$PWD/kcms/kfontinst/kcmfontinst/FontsPackage.h \
   $$PWD/kcms/kfontinst/kcmfontinst/GroupList.h \
   $$PWD/kcms/kfontinst/kcmfontinst/JobRunner.h \
   $$PWD/kcms/kfontinst/kcmfontinst/KCmFontInst.h \
   $$PWD/kcms/kfontinst/kcmfontinst/PreviewList.h \
   $$PWD/kcms/kfontinst/kcmfontinst/PrintDialog.h \
   $$PWD/kcms/kfontinst/kio/FontInstInterface.h \
   $$PWD/kcms/kfontinst/kio/KioFonts.h \
   $$PWD/kcms/kfontinst/lib/Family.h \
   $$PWD/kcms/kfontinst/lib/Fc.h \
   $$PWD/kcms/kfontinst/lib/FcEngine.h \
   $$PWD/kcms/kfontinst/lib/File.h \
   $$PWD/kcms/kfontinst/lib/KfiConstants.h \
   $$PWD/kcms/kfontinst/lib/kfontinst_export.h \
   $$PWD/kcms/kfontinst/lib/Misc.h \
   $$PWD/kcms/kfontinst/lib/Style.h \
   $$PWD/kcms/kfontinst/lib/WritingSystems.h \
   $$PWD/kcms/kfontinst/lib/XmlStrings.h \
   $$PWD/kcms/kfontinst/thumbnail/FontThumbnail.h \
   $$PWD/kcms/kfontinst/viewpart/CharTip.h \
   $$PWD/kcms/kfontinst/viewpart/FontPreview.h \
   $$PWD/kcms/kfontinst/viewpart/FontViewPart.h \
   $$PWD/kcms/kfontinst/viewpart/PreviewSelectAction.h \
   $$PWD/kcms/kfontinst/viewpart/UnicodeBlocks.h \
   $$PWD/kcms/kfontinst/viewpart/UnicodeCategories.h \
   $$PWD/kcms/kfontinst/viewpart/UnicodeScripts.h \
   $$PWD/kcms/krdb/krdb.h \
   $$PWD/kcms/lookandfeel/kcm.h \
   $$PWD/kcms/lookandfeel/lookandfeeldata.h \
   $$PWD/kcms/style/gtkpage.h \
   $$PWD/kcms/style/gtkthemesmodel.h \
   $$PWD/kcms/style/kcmstyle.h \
   $$PWD/kcms/style/previewitem.h \
   $$PWD/kcms/style/styleconfdialog.h \
   $$PWD/kcms/style/styledata.h \
   $$PWD/kcms/style/stylesmodel.h \
   $$PWD/kcms/translations/translations.h \
   $$PWD/kcms/translations/translationsmodel.h \
   $$PWD/kcms/translations/translationssettings.h \
   $$PWD/kioslave/desktop/desktopnotifier.h \
   $$PWD/kioslave/desktop/kio_desktop.h \
   $$PWD/klipper/systemclipboard/qtclipboard.h \
   $$PWD/klipper/systemclipboard/systemclipboard.h \
   $$PWD/klipper/systemclipboard/waylandclipboard.h \
   $$PWD/klipper/actionstreewidget.h \
   $$PWD/klipper/clipboardengine.h \
   $$PWD/klipper/clipboardjob.h \
   $$PWD/klipper/clipboardservice.h \
   $$PWD/klipper/clipcommandprocess.h \
   $$PWD/klipper/configdialog.h \
   $$PWD/klipper/editactiondialog.h \
   $$PWD/klipper/history.h \
   $$PWD/klipper/historyimageitem.h \
   $$PWD/klipper/historyitem.h \
   $$PWD/klipper/historymodel.h \
   $$PWD/klipper/historystringitem.h \
   $$PWD/klipper/historyurlitem.h \
   $$PWD/klipper/klipper.h \
   $$PWD/klipper/klipperpopup.h \
   $$PWD/klipper/popupproxy.h \
   $$PWD/klipper/tray.h \
   $$PWD/klipper/urlgrabber.h \
   $$PWD/krunner/view.h \
   $$PWD/ksmserver/client.h \
   $$PWD/ksmserver/global.h \
   $$PWD/ksmserver/server.h \
   $$PWD/ksplash/ksplashqml/splashapp.h \
   $$PWD/ksplash/ksplashqml/splashwindow.h \
   $$PWD/ktimezoned/ktimezoned.h \
   $$PWD/ktimezoned/ktimezoned_win.h \
   $$PWD/ktimezoned/ktimezonedbase.h \
   $$PWD/libcolorcorrect/autotests/mock_kwin.h \
   $$PWD/libcolorcorrect/autotests/qtest_dbus.h \
   $$PWD/libcolorcorrect/declarative/colorcorrectplugin.h \
   $$PWD/libcolorcorrect/kded/locationupdater.h \
   $$PWD/libcolorcorrect/colorcorrectconstants.h \
   $$PWD/libcolorcorrect/compositorcoloradaptor.h \
   $$PWD/libcolorcorrect/geolocator.h \
   $$PWD/libcolorcorrect/suncalc.h \
   $$PWD/libdbusmenuqt/dbusmenuimporter.h \
   $$PWD/libdbusmenuqt/dbusmenushortcut_p.h \
   $$PWD/libdbusmenuqt/dbusmenutypes_p.h \
   $$PWD/libdbusmenuqt/utils_p.h \
   $$PWD/libkworkspace/kdisplaymanager.h \
   $$PWD/libkworkspace/kworkspace.h \
   $$PWD/libkworkspace/loginddbustypes.h \
   $$PWD/libkworkspace/sessionmanagement.h \
   $$PWD/libkworkspace/sessionmanagementbackend.h \
   $$PWD/libkworkspace/updatelaunchenvjob.h \
   $$PWD/libnotificationmanager/declarative/notificationmanagerplugin.h \
   $$PWD/libnotificationmanager/abstractnotificationsmodel.h \
   $$PWD/libnotificationmanager/abstractnotificationsmodel_p.h \
   $$PWD/libnotificationmanager/job.h \
   $$PWD/libnotificationmanager/job_p.h \
   $$PWD/libnotificationmanager/jobsmodel.h \
   $$PWD/libnotificationmanager/jobsmodel_p.h \
   $$PWD/libnotificationmanager/limitedrowcountproxymodel_p.h \
   $$PWD/libnotificationmanager/mirroredscreenstracker_p.h \
   $$PWD/libnotificationmanager/notification.h \
   $$PWD/libnotificationmanager/notification_p.h \
   $$PWD/libnotificationmanager/notificationfilterproxymodel_p.h \
   $$PWD/libnotificationmanager/notificationgroupcollapsingproxymodel_p.h \
   $$PWD/libnotificationmanager/notificationgroupingproxymodel_p.h \
   $$PWD/libnotificationmanager/notifications.h \
   $$PWD/libnotificationmanager/notificationsmodel.h \
   $$PWD/libnotificationmanager/notificationsortproxymodel_p.h \
   $$PWD/libnotificationmanager/server.h \
   $$PWD/libnotificationmanager/server_p.h \
   $$PWD/libnotificationmanager/serverinfo.h \
   $$PWD/libnotificationmanager/settings.h \
   $$PWD/libnotificationmanager/utils_p.h \
   $$PWD/libnotificationmanager/watchednotificationsmodel.h \
   $$PWD/libtaskmanager/declarative/pipewirecore.h \
   $$PWD/libtaskmanager/declarative/pipewiresourceitem.h \
   $$PWD/libtaskmanager/declarative/pipewiresourcestream.h \
   $$PWD/libtaskmanager/declarative/screencasting.h \
   $$PWD/libtaskmanager/declarative/screencastingrequest.h \
   $$PWD/libtaskmanager/declarative/taskmanagerplugin.h \
   $$PWD/libtaskmanager/abstracttasksmodel.h \
   $$PWD/libtaskmanager/abstracttasksmodeliface.h \
   $$PWD/libtaskmanager/abstracttasksproxymodeliface.h \
   $$PWD/libtaskmanager/abstractwindowtasksmodel.h \
   $$PWD/libtaskmanager/activityinfo.h \
   $$PWD/libtaskmanager/concatenatetasksproxymodel.h \
   $$PWD/libtaskmanager/flattentaskgroupsproxymodel.h \
   $$PWD/libtaskmanager/launchertasksmodel.h \
   $$PWD/libtaskmanager/launchertasksmodel_p.h \
   $$PWD/libtaskmanager/startuptasksmodel.h \
   $$PWD/libtaskmanager/taskfilterproxymodel.h \
   $$PWD/libtaskmanager/taskgroupingproxymodel.h \
   $$PWD/libtaskmanager/tasksmodel.h \
   $$PWD/libtaskmanager/tasktools.h \
   $$PWD/libtaskmanager/virtualdesktopinfo.h \
   $$PWD/libtaskmanager/waylandtasksmodel.h \
   $$PWD/libtaskmanager/windowtasksmodel.h \
   $$PWD/libtaskmanager/xwindowsystemeventbatcher.h \
   $$PWD/libtaskmanager/xwindowtasksmodel.h \
   $$PWD/logout-greeter/greeter.h \
   $$PWD/logout-greeter/shutdowndlg.h \
   $$PWD/phonon/platform_kde/debug.h \
   $$PWD/phonon/platform_kde/kdeplatformplugin.h \
   $$PWD/phonon/platform_kde/kiomediastream.h \
   $$PWD/phonon/platform_kde/kiomediastream_p.h \
   $$PWD/plasma-windowed/plasmawindowedcorona.h \
   $$PWD/plasma-windowed/plasmawindowedview.h \
   $$PWD/plasmacalendarintegration/qmlhelper/holidayeventshelperplugin.h \
   $$PWD/plasmacalendarintegration/holidaysevents.h \
   $$PWD/runners/activities/activityrunner.h \
   $$PWD/runners/appstream/appstreamrunner.h \
   $$PWD/runners/baloo/baloosearchrunner.h \
   $$PWD/runners/baloo/dbusutils_p.h \
   $$PWD/runners/bookmarks/browsers/browser.h \
   $$PWD/runners/bookmarks/browsers/chrome.h \
   $$PWD/runners/bookmarks/browsers/chromefindprofile.h \
   $$PWD/runners/bookmarks/browsers/falkon.h \
   $$PWD/runners/bookmarks/browsers/findprofile.h \
   $$PWD/runners/bookmarks/browsers/firefox.h \
   $$PWD/runners/bookmarks/browsers/kdebrowser.h \
   $$PWD/runners/bookmarks/browsers/opera.h \
   $$PWD/runners/bookmarks/tests/testchromebookmarks.h \
   $$PWD/runners/bookmarks/bookmarkmatch.h \
   $$PWD/runners/bookmarks/bookmarksrunner.h \
   $$PWD/runners/bookmarks/bookmarksrunner_defs.h \
   $$PWD/runners/bookmarks/browserfactory.h \
   $$PWD/runners/bookmarks/favicon.h \
   $$PWD/runners/bookmarks/faviconfromblob.h \
   $$PWD/runners/bookmarks/fetchsqlite.h \
   $$PWD/runners/calculator/calculatorrunner.h \
   $$PWD/runners/calculator/qalculate_engine.h \
   $$PWD/runners/kill/config_keys.h \
   $$PWD/runners/kill/killrunner.h \
   $$PWD/runners/kill/killrunner_config.h \
   $$PWD/runners/locations/locationrunner.h \
   $$PWD/runners/places/placesrunner.h \
   $$PWD/runners/powerdevil/PowerDevilRunner.h \
   $$PWD/runners/recentdocuments/recentdocuments.h \
   $$PWD/runners/services/servicerunner.h \
   $$PWD/runners/sessions/sessionrunner.h \
   $$PWD/runners/shell/shellrunner.h \
   $$PWD/runners/webshortcuts/webshortcutrunner.h \
   $$PWD/runners/windowedwidgets/windowedwidgetsrunner.h \
   $$PWD/runners/windows/windowsrunner.h \
   $$PWD/shell/autotests/desktopview.h \
   $$PWD/shell/packageplugins/layouttemplate/layouttemplate.h \
   $$PWD/shell/packageplugins/lookandfeel/lookandfeel.h \
   $$PWD/shell/packageplugins/qmlWallpaper/wallpaper.h \
   $$PWD/shell/packageplugins/shell/shellpackage.h \
   $$PWD/shell/packageplugins/wallpaperimages/wallpaperpackage.h \
   $$PWD/shell/scripting/appinterface.h \
   $$PWD/shell/scripting/applet.h \
   $$PWD/shell/scripting/configgroup.h \
   $$PWD/shell/scripting/containment.h \
   $$PWD/shell/scripting/panel.h \
   $$PWD/shell/scripting/scriptengine.h \
   $$PWD/shell/scripting/scriptengine_v1.h \
   $$PWD/shell/scripting/widget.h \
   $$PWD/shell/alternativeshelper.h \
   $$PWD/shell/containmentconfigview.h \
   $$PWD/shell/coronatesthelper.h \
   $$PWD/shell/currentcontainmentactionsmodel.h \
   $$PWD/shell/desktopview.h \
   $$PWD/shell/futureutil.h \
   $$PWD/shell/osd.h \
   $$PWD/shell/panelconfigview.h \
   $$PWD/shell/panelshadows_p.h \
   $$PWD/shell/panelview.h \
   $$PWD/shell/screenpool.h \
   $$PWD/shell/shellcorona.h \
   $$PWD/shell/softwarerendernotifier.h \
   $$PWD/shell/standaloneappcorona.h \
   $$PWD/shell/strutmanager.h \
   $$PWD/shell/userfeedback.h \
   $$PWD/solidautoeject/solidautoeject.h \
   $$PWD/soliduiserver/soliduiserver.h \
   $$PWD/startkde/kcheckrunning/kcheckrunning.h \
   $$PWD/startkde/kcminit/main.h \
   $$PWD/startkde/plasma-session/autostart.h \
   $$PWD/startkde/plasma-session/startup.h \
   $$PWD/startkde/plasma-shutdown/shutdown.h \
   $$PWD/startkde/waitforname/waiter.h \
   $$PWD/startkde/startplasma.h \
   $$PWD/statusnotifierwatcher/statusnotifierwatcher.h \
   $$PWD/statusnotifierwatcher/systemtraytypedefs.h \
   $$PWD/systemmonitor/kdedksysguard.h \
   $$PWD/systemmonitor/ksystemactivitydialog.h \
   $$PWD/templates/ion-dataengine/src/ion-%{APPNAMELC}.h \
   $$PWD/wallpapers/image/backgroundlistmodel.h \
   $$PWD/wallpapers/image/image.h \
   $$PWD/wallpapers/image/imageplugin.h \
   $$PWD/wallpapers/image/slidefiltermodel.h \
   $$PWD/wallpapers/image/slidemodel.h \
   $$PWD/xembed-sni-proxy/fdoselectionmanager.h \
   $$PWD/xembed-sni-proxy/snidbus.h \
   $$PWD/xembed-sni-proxy/sniproxy.h \
   $$PWD/xembed-sni-proxy/xcbutils.h \
   $$PWD/xembed-sni-proxy/xtestsender.h \
   shell/gesturedispatcher.h \
   shell/globalgestureserver.h \
   shell/globalgesturetypes.h \
   shell/toast.h

SOURCES = \
   $$PWD/applets/activitybar/contents/ui/main.qml \
   $$PWD/applets/analog-clock/contents/config/config.qml \
   $$PWD/applets/analog-clock/contents/ui/analogclock.qml \
   $$PWD/applets/analog-clock/contents/ui/configGeneral.qml \
   $$PWD/applets/analog-clock/contents/ui/Hand.qml \
   $$PWD/applets/appmenu/lib/appmenuapplet.cpp \
   $$PWD/applets/appmenu/package/contents/config/config.qml \
   $$PWD/applets/appmenu/package/contents/ui/configGeneral.qml \
   $$PWD/applets/appmenu/package/contents/ui/main.qml \
   $$PWD/applets/appmenu/plugin/appmenumodel.cpp \
   $$PWD/applets/appmenu/plugin/appmenuplugin.cpp \
   $$PWD/applets/batterymonitor/package/contents/config/config.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/BadgeOverlay.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/BatteryItem.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/batterymonitor.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/BrightnessItem.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/CompactRepresentation.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/ConfigGeneral.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/InhibitionHint.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/PopupDialog.qml \
   $$PWD/applets/batterymonitor/package/contents/ui/PowerManagementItem.qml \
   $$PWD/applets/calendar/package/contents/config/config.qml \
   $$PWD/applets/calendar/package/contents/ui/configAgenda.qml \
   $$PWD/applets/calendar/package/contents/ui/configGeneral.qml \
   $$PWD/applets/calendar/package/contents/ui/main.qml \
   $$PWD/applets/calendar/calendarapplet.cpp \
   $$PWD/applets/clipboard/contents/ui/BarcodePage.qml \
   $$PWD/applets/clipboard/contents/ui/clipboard.qml \
   $$PWD/applets/clipboard/contents/ui/ClipboardItemDelegate.qml \
   $$PWD/applets/clipboard/contents/ui/ClipboardPage.qml \
   $$PWD/applets/clipboard/contents/ui/DelegateToolButtons.qml \
   $$PWD/applets/clipboard/contents/ui/ImageItemDelegate.qml \
   $$PWD/applets/clipboard/contents/ui/Menu.qml \
   $$PWD/applets/clipboard/contents/ui/TextItemDelegate.qml \
   $$PWD/applets/clipboard/contents/ui/UrlItemDelegate.qml \
   $$PWD/applets/devicenotifier/package/contents/ui/DeviceItem.qml \
   $$PWD/applets/devicenotifier/package/contents/ui/devicenotifier.qml \
   $$PWD/applets/devicenotifier/package/contents/ui/FullRepresentation.qml \
   $$PWD/applets/digital-clock/package/contents/config/config.qml \
   $$PWD/applets/digital-clock/package/contents/ui/CalendarView.qml \
   $$PWD/applets/digital-clock/package/contents/ui/configAppearance.qml \
   $$PWD/applets/digital-clock/package/contents/ui/configCalendar.qml \
   $$PWD/applets/digital-clock/package/contents/ui/configTimeZones.qml \
   $$PWD/applets/digital-clock/package/contents/ui/DigitalClock.qml \
   $$PWD/applets/digital-clock/package/contents/ui/main.qml \
   $$PWD/applets/digital-clock/package/contents/ui/MonthMenu.qml \
   $$PWD/applets/digital-clock/package/contents/ui/Tooltip.qml \
   $$PWD/applets/digital-clock/plugin/clipboardmenu.cpp \
   $$PWD/applets/digital-clock/plugin/digitalclockplugin.cpp \
   $$PWD/applets/digital-clock/plugin/timezonemodel.cpp \
   $$PWD/applets/digital-clock/plugin/timezonesi18n.cpp \
   $$PWD/applets/icon/package/contents/ui/main.qml \
   $$PWD/applets/icon/iconapplet.cpp \
   $$PWD/applets/kicker/plugin/abstractentry.cpp \
   $$PWD/applets/kicker/plugin/abstractmodel.cpp \
   $$PWD/applets/kicker/plugin/actionlist.cpp \
   $$PWD/applets/kicker/plugin/appentry.cpp \
   $$PWD/applets/kicker/plugin/appsmodel.cpp \
   $$PWD/applets/kicker/plugin/computermodel.cpp \
   $$PWD/applets/kicker/plugin/contactentry.cpp \
   $$PWD/applets/kicker/plugin/containmentinterface.cpp \
   $$PWD/applets/kicker/plugin/dashboardwindow.cpp \
   $$PWD/applets/kicker/plugin/draghelper.cpp \
   $$PWD/applets/kicker/plugin/fileentry.cpp \
   $$PWD/applets/kicker/plugin/forwardingmodel.cpp \
   $$PWD/applets/kicker/plugin/funnelmodel.cpp \
   $$PWD/applets/kicker/plugin/kastatsfavoritesmodel.cpp \
   $$PWD/applets/kicker/plugin/kickerplugin.cpp \
   $$PWD/applets/kicker/plugin/menuentryeditor.cpp \
   $$PWD/applets/kicker/plugin/placeholdermodel.cpp \
   $$PWD/applets/kicker/plugin/processrunner.cpp \
   $$PWD/applets/kicker/plugin/recentcontactsmodel.cpp \
   $$PWD/applets/kicker/plugin/recentusagemodel.cpp \
   $$PWD/applets/kicker/plugin/rootmodel.cpp \
   $$PWD/applets/kicker/plugin/runnermatchesmodel.cpp \
   $$PWD/applets/kicker/plugin/runnermodel.cpp \
   $$PWD/applets/kicker/plugin/simplefavoritesmodel.cpp \
   $$PWD/applets/kicker/plugin/submenu.cpp \
   $$PWD/applets/kicker/plugin/systementry.cpp \
   $$PWD/applets/kicker/plugin/systemmodel.cpp \
   $$PWD/applets/kicker/plugin/systemsettings.cpp \
   $$PWD/applets/kicker/plugin/wheelinterceptor.cpp \
   $$PWD/applets/kicker/plugin/windowsystem.cpp \
   $$PWD/applets/lock_logout/contents/config/config.qml \
   $$PWD/applets/lock_logout/contents/ui/ConfigGeneral.qml \
   $$PWD/applets/lock_logout/contents/ui/lockout.qml \
   $$PWD/applets/mediacontroller/contents/ui/ExpandedRepresentation.qml \
   $$PWD/applets/mediacontroller/contents/ui/main.qml \
   $$PWD/applets/notifications/package/contents/ui/global/Globals.qml \
   $$PWD/applets/notifications/package/contents/ui/global/PulseAudio.qml \
   $$PWD/applets/notifications/package/contents/ui/CompactRepresentation.qml \
   $$PWD/applets/notifications/package/contents/ui/DraggableDelegate.qml \
   $$PWD/applets/notifications/package/contents/ui/DraggableFileArea.qml \
   $$PWD/applets/notifications/package/contents/ui/EditContextMenu.qml \
   $$PWD/applets/notifications/package/contents/ui/FullRepresentation.qml \
   $$PWD/applets/notifications/package/contents/ui/JobDetails.qml \
   $$PWD/applets/notifications/package/contents/ui/JobItem.qml \
   $$PWD/applets/notifications/package/contents/ui/main.qml \
   $$PWD/applets/notifications/package/contents/ui/NotificationHeader.qml \
   $$PWD/applets/notifications/package/contents/ui/NotificationItem.qml \
   $$PWD/applets/notifications/package/contents/ui/NotificationPopup.qml \
   $$PWD/applets/notifications/package/contents/ui/NotificationReplyField.qml \
   $$PWD/applets/notifications/package/contents/ui/SelectableLabel.qml \
   $$PWD/applets/notifications/package/contents/ui/ThumbnailStrip.qml \
   $$PWD/applets/notifications/filemenu.cpp \
   $$PWD/applets/notifications/globalshortcuts.cpp \
   $$PWD/applets/notifications/notificationapplet.cpp \
   $$PWD/applets/notifications/thumbnailer.cpp \
   $$PWD/applets/panelspacer/package/contents/ui/main.qml \
   $$PWD/applets/panelspacer/plugin/panelspacer.cpp \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/config/config.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/config/ConfigAppearance.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/config/ConfigSensors.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/config/FaceDetails.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/CompactRepresentation.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/FullRepresentation.qml \
   $$PWD/applets/systemmonitor/systemmonitor/package/contents/ui/main.qml \
   $$PWD/applets/systemmonitor/systemmonitor/systemmonitor.cpp \
   $$PWD/applets/systemtray/container/package/contents/ui/main.qml \
   $$PWD/applets/systemtray/container/systemtraycontainer.cpp \
   $$PWD/applets/systemtray/package/contents/applet/CompactApplet.qml \
   $$PWD/applets/systemtray/package/contents/config/config.qml \
   $$PWD/applets/systemtray/package/contents/ui/items/AbstractItem.qml \
   $$PWD/applets/systemtray/package/contents/ui/items/ItemLoader.qml \
   $$PWD/applets/systemtray/package/contents/ui/items/PlasmoidItem.qml \
   $$PWD/applets/systemtray/package/contents/ui/items/PulseAnimation.qml \
   $$PWD/applets/systemtray/package/contents/ui/items/StatusNotifierItem.qml \
   $$PWD/applets/systemtray/package/contents/ui/ConfigEntries.qml \
   $$PWD/applets/systemtray/package/contents/ui/ConfigGeneral.qml \
   $$PWD/applets/systemtray/package/contents/ui/CurrentItemHighLight.qml \
   $$PWD/applets/systemtray/package/contents/ui/ExpandedRepresentation.qml \
   $$PWD/applets/systemtray/package/contents/ui/ExpanderArrow.qml \
   $$PWD/applets/systemtray/package/contents/ui/HiddenItemsView.qml \
   $$PWD/applets/systemtray/package/contents/ui/main.qml \
   $$PWD/applets/systemtray/package/contents/ui/PlasmoidPopupsContainer.qml \
   $$PWD/applets/systemtray/tests/statusnotifier/main.cpp \
   $$PWD/applets/systemtray/tests/statusnotifier/pumpjob.cpp \
   $$PWD/applets/systemtray/tests/statusnotifier/statusnotifiertest.cpp \
   $$PWD/applets/systemtray/sortedsystemtraymodel.cpp \
   $$PWD/applets/systemtray/systemtray.cpp \
   $$PWD/applets/systemtray/systemtraymodel.cpp \
   $$PWD/appmenu/appmenu.cpp \
   $$PWD/appmenu/appmenu_dbus.cpp \
   $$PWD/appmenu/menuimporter.cpp \
   $$PWD/appmenu/verticalmenu.cpp \
   $$PWD/cmake-build-debug/CMakeFiles/3.17.3/CompilerIdC/CMakeCCompilerId.c \
   $$PWD/cmake-build-debug/CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/components/containmentlayoutmanager/qml/private/BasicResizeHandle.qml \
   $$PWD/components/containmentlayoutmanager/qml/BasicAppletContainer.qml \
   $$PWD/components/containmentlayoutmanager/qml/ConfigOverlayWithHandles.qml \
   $$PWD/components/containmentlayoutmanager/qml/PlaceHolder.qml \
   $$PWD/components/containmentlayoutmanager/abstractlayoutmanager.cpp \
   $$PWD/components/containmentlayoutmanager/appletcontainer.cpp \
   $$PWD/components/containmentlayoutmanager/appletslayout.cpp \
   $$PWD/components/containmentlayoutmanager/configoverlay.cpp \
   $$PWD/components/containmentlayoutmanager/containmentlayoutmanagerplugin.cpp \
   $$PWD/components/containmentlayoutmanager/gridlayoutmanager.cpp \
   $$PWD/components/containmentlayoutmanager/itemcontainer.cpp \
   $$PWD/components/containmentlayoutmanager/resizehandle.cpp \
   $$PWD/components/keyboardlayout/keyboardlayout.cpp \
   $$PWD/components/keyboardlayout/keyboardlayoutplugin.cpp \
   $$PWD/components/sessionsprivate/sessionsmodel.cpp \
   $$PWD/components/sessionsprivate/sessionsprivateplugin.cpp \
   $$PWD/components/shellprivate/interactiveconsole/interactiveconsole.cpp \
   $$PWD/components/shellprivate/wallpaperplugin/wallpaperplugin.cpp \
   $$PWD/components/shellprivate/widgetexplorer/kcategorizeditemsviewmodels.cpp \
   $$PWD/components/shellprivate/widgetexplorer/openwidgetassistant.cpp \
   $$PWD/components/shellprivate/widgetexplorer/plasmaappletitemmodel.cpp \
   $$PWD/components/shellprivate/widgetexplorer/widgetexplorer.cpp \
   $$PWD/components/shellprivate/shellprivateplugin.cpp \
   $$PWD/components/tests/sessions.qml \
   $$PWD/components/workspace/BatteryIcon.qml \
   $$PWD/containmentactions/applauncher/launch.cpp \
   $$PWD/containmentactions/contextmenu/menu.cpp \
   $$PWD/containmentactions/paste/paste.cpp \
   $$PWD/containmentactions/switchactivity/switch.cpp \
   $$PWD/containmentactions/switchdesktop/desktop.cpp \
   $$PWD/containmentactions/switchwindow/switch.cpp \
   $$PWD/dataengines/activities/ActivityData.cpp \
   $$PWD/dataengines/activities/activityengine.cpp \
   $$PWD/dataengines/activities/activityjob.cpp \
   $$PWD/dataengines/activities/activityservice.cpp \
   $$PWD/dataengines/applicationjobs/jobaction.cpp \
   $$PWD/dataengines/applicationjobs/jobcontrol.cpp \
   $$PWD/dataengines/applicationjobs/kuiserverengine.cpp \
   $$PWD/dataengines/apps/appjob.cpp \
   $$PWD/dataengines/apps/appsengine.cpp \
   $$PWD/dataengines/apps/appservice.cpp \
   $$PWD/dataengines/apps/appsource.cpp \
   $$PWD/dataengines/devicenotifications/devicenotificationsengine.cpp \
   $$PWD/dataengines/devicenotifications/ksolidnotify.cpp \
   $$PWD/dataengines/dict/dictengine.cpp \
   $$PWD/dataengines/executable/executable.cpp \
   $$PWD/dataengines/favicons/faviconprovider.cpp \
   $$PWD/dataengines/favicons/favicons.cpp \
   $$PWD/dataengines/filebrowser/filebrowserengine.cpp \
   $$PWD/dataengines/geolocation/geolocation.cpp \
   $$PWD/dataengines/geolocation/geolocationprovider.cpp \
   $$PWD/dataengines/geolocation/location_gps.cpp \
   $$PWD/dataengines/geolocation/location_ip.cpp \
   $$PWD/dataengines/hotplug/deviceaction.cpp \
   $$PWD/dataengines/hotplug/deviceserviceaction.cpp \
   $$PWD/dataengines/hotplug/hotplugengine.cpp \
   $$PWD/dataengines/hotplug/hotplugjob.cpp \
   $$PWD/dataengines/hotplug/hotplugservice.cpp \
   $$PWD/dataengines/keystate/keyservice.cpp \
   $$PWD/dataengines/keystate/keystate.cpp \
   $$PWD/dataengines/mouse/cursornotificationhandler.cpp \
   $$PWD/dataengines/mouse/mouseengine.cpp \
   $$PWD/dataengines/mpris2/mpris2engine.cpp \
   $$PWD/dataengines/mpris2/multiplexedservice.cpp \
   $$PWD/dataengines/mpris2/multiplexer.cpp \
   $$PWD/dataengines/mpris2/playeractionjob.cpp \
   $$PWD/dataengines/mpris2/playercontainer.cpp \
   $$PWD/dataengines/mpris2/playercontrol.cpp \
   $$PWD/dataengines/notifications/notificationaction.cpp \
   $$PWD/dataengines/notifications/notificationsengine.cpp \
   $$PWD/dataengines/notifications/notificationservice.cpp \
   $$PWD/dataengines/packagekit/packagekitengine.cpp \
   $$PWD/dataengines/packagekit/packagekitjob.cpp \
   $$PWD/dataengines/packagekit/packagekitservice.cpp \
   $$PWD/dataengines/places/placesengine.cpp \
   $$PWD/dataengines/places/placeservice.cpp \
   $$PWD/dataengines/places/placesproxymodel.cpp \
   $$PWD/dataengines/places/setupdevicejob.cpp \
   $$PWD/dataengines/powermanagement/powermanagementengine.cpp \
   $$PWD/dataengines/powermanagement/powermanagementjob.cpp \
   $$PWD/dataengines/powermanagement/powermanagementservice.cpp \
   $$PWD/dataengines/soliddevice/devicesignalmapmanager.cpp \
   $$PWD/dataengines/soliddevice/devicesignalmapper.cpp \
   $$PWD/dataengines/soliddevice/hddtemp.cpp \
   $$PWD/dataengines/soliddevice/soliddeviceengine.cpp \
   $$PWD/dataengines/soliddevice/soliddevicejob.cpp \
   $$PWD/dataengines/soliddevice/soliddeviceservice.cpp \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritem_engine.cpp \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemjob.cpp \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemservice.cpp \
   $$PWD/dataengines/statusnotifieritem/statusnotifieritemsource.cpp \
   $$PWD/dataengines/statusnotifieritem/systemtraytypes.cpp \
   $$PWD/dataengines/systemmonitor/systemmonitor.cpp \
   $$PWD/dataengines/time/solarsystem.cpp \
   $$PWD/dataengines/time/timeengine.cpp \
   $$PWD/dataengines/time/timesource.cpp \
   $$PWD/dataengines/weather/ions/bbcukmet/ion_bbcukmet.cpp \
   $$PWD/dataengines/weather/ions/envcan/ion_envcan.cpp \
   $$PWD/dataengines/weather/ions/noaa/ion_noaa.cpp \
   $$PWD/dataengines/weather/ions/wetter.com/ion_wettercom.cpp \
   $$PWD/dataengines/weather/ions/ion.cpp \
   $$PWD/dataengines/weather/weatherengine.cpp \
   $$PWD/freespacenotifier/freespacenotifier.cpp \
   $$PWD/freespacenotifier/module.cpp \
   $$PWD/gmenu-dbusmenu-proxy/actions.cpp \
   $$PWD/gmenu-dbusmenu-proxy/gdbusmenutypes_p.cpp \
   $$PWD/gmenu-dbusmenu-proxy/icons.cpp \
   $$PWD/gmenu-dbusmenu-proxy/main.cpp \
   $$PWD/gmenu-dbusmenu-proxy/menu.cpp \
   $$PWD/gmenu-dbusmenu-proxy/menuproxy.cpp \
   $$PWD/gmenu-dbusmenu-proxy/utils.cpp \
   $$PWD/gmenu-dbusmenu-proxy/window.cpp \
   $$PWD/kcms/colors/editor/kcolorschemeeditor.cpp \
   $$PWD/kcms/colors/editor/previewwidget.cpp \
   $$PWD/kcms/colors/editor/scmeditorcolors.cpp \
   $$PWD/kcms/colors/editor/scmeditordialog.cpp \
   $$PWD/kcms/colors/editor/scmeditoreffects.cpp \
   $$PWD/kcms/colors/editor/scmeditoroptions.cpp \
   $$PWD/kcms/colors/editor/setpreviewwidget.cpp \
   $$PWD/kcms/colors/package/contents/ui/main.qml \
   $$PWD/kcms/colors/colors.cpp \
   $$PWD/kcms/colors/colorsdata.cpp \
   $$PWD/kcms/colors/colorsmodel.cpp \
   $$PWD/kcms/colors/filterproxymodel.cpp \
   $$PWD/kcms/cursortheme/package/contents/ui/Delegate.qml \
   $$PWD/kcms/cursortheme/package/contents/ui/main.qml \
   $$PWD/kcms/cursortheme/xcursor/cursortheme.cpp \
   $$PWD/kcms/cursortheme/xcursor/previewwidget.cpp \
   $$PWD/kcms/cursortheme/xcursor/sortproxymodel.cpp \
   $$PWD/kcms/cursortheme/xcursor/thememodel.cpp \
   $$PWD/kcms/cursortheme/xcursor/xcursortheme.cpp \
   $$PWD/kcms/cursortheme/cursorthemedata.cpp \
   $$PWD/kcms/cursortheme/kcmcursortheme.cpp \
   $$PWD/kcms/desktoptheme/package/contents/ui/Hand.qml \
   $$PWD/kcms/desktoptheme/package/contents/ui/main.qml \
   $$PWD/kcms/desktoptheme/package/contents/ui/ThemePreview.qml \
   $$PWD/kcms/desktoptheme/desktopthemedata.cpp \
   $$PWD/kcms/desktoptheme/filterproxymodel.cpp \
   $$PWD/kcms/desktoptheme/kcm.cpp \
   $$PWD/kcms/desktoptheme/themesmodel.cpp \
   $$PWD/kcms/feedback/package/contents/ui/main.qml \
   $$PWD/kcms/feedback/feedback.cpp \
   $$PWD/kcms/fonts/package/contents/ui/ContextualHelpButton.qml \
   $$PWD/kcms/fonts/package/contents/ui/FontWidget.qml \
   $$PWD/kcms/fonts/package/contents/ui/main.qml \
   $$PWD/kcms/fonts/fonts.cpp \
   $$PWD/kcms/fonts/fontsaasettings.cpp \
   $$PWD/kcms/fonts/fontsdata.cpp \
   $$PWD/kcms/fonts/kxftconfig.cpp \
   $$PWD/kcms/fonts/previewimageprovider.cpp \
   $$PWD/kcms/fonts/previewrenderengine.cpp \
   $$PWD/kcms/icons/package/contents/ui/IconSizePopup.qml \
   $$PWD/kcms/icons/package/contents/ui/main.qml \
   $$PWD/kcms/icons/changeicons.cpp \
   $$PWD/kcms/icons/iconsdata.cpp \
   $$PWD/kcms/icons/iconsizecategorymodel.cpp \
   $$PWD/kcms/icons/iconsmodel.cpp \
   $$PWD/kcms/icons/iconssettings.cpp \
   $$PWD/kcms/icons/main.cpp \
   $$PWD/kcms/kfontinst/apps/Installer.cpp \
   $$PWD/kcms/kfontinst/apps/Printer.cpp \
   $$PWD/kcms/kfontinst/apps/Viewer.cpp \
   $$PWD/kcms/kfontinst/dbus/FcConfig.cpp \
   $$PWD/kcms/kfontinst/dbus/Folder.cpp \
   $$PWD/kcms/kfontinst/dbus/FontInst.cpp \
   $$PWD/kcms/kfontinst/dbus/FontinstIface.cpp \
   $$PWD/kcms/kfontinst/dbus/Helper.cpp \
   $$PWD/kcms/kfontinst/dbus/Main.cpp \
   $$PWD/kcms/kfontinst/dbus/Utils.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/ActionLabel.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/DuplicatesDialog.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/FcQuery.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/FontFilter.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/FontFilterProxyStyle.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/FontList.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/FontsPackage.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/GroupList.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/JobRunner.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/KCmFontInst.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/PreviewList.cpp \
   $$PWD/kcms/kfontinst/kcmfontinst/PrintDialog.cpp \
   $$PWD/kcms/kfontinst/kio/autotests/test_kio_fonts.cpp \
   $$PWD/kcms/kfontinst/kio/FontInstInterface.cpp \
   $$PWD/kcms/kfontinst/kio/KioFonts.cpp \
   $$PWD/kcms/kfontinst/lib/Family.cpp \
   $$PWD/kcms/kfontinst/lib/Fc.cpp \
   $$PWD/kcms/kfontinst/lib/FcEngine.cpp \
   $$PWD/kcms/kfontinst/lib/File.cpp \
   $$PWD/kcms/kfontinst/lib/Misc.cpp \
   $$PWD/kcms/kfontinst/lib/Style.cpp \
   $$PWD/kcms/kfontinst/lib/WritingSystems.cpp \
   $$PWD/kcms/kfontinst/thumbnail/FontThumbnail.cpp \
   $$PWD/kcms/kfontinst/viewpart/CharTip.cpp \
   $$PWD/kcms/kfontinst/viewpart/FontPreview.cpp \
   $$PWD/kcms/kfontinst/viewpart/FontViewPart.cpp \
   $$PWD/kcms/kfontinst/viewpart/PreviewSelectAction.cpp \
   $$PWD/kcms/krdb/krdb.cpp \
   $$PWD/kcms/krdb/krdb_clearlibrarypath.cpp \
   $$PWD/kcms/lookandfeel/autotests/kcmtest.cpp \
   $$PWD/kcms/lookandfeel/package/contents/ui/main.qml \
   $$PWD/kcms/lookandfeel/kcm.cpp \
   $$PWD/kcms/lookandfeel/kcmmain.cpp \
   $$PWD/kcms/lookandfeel/lnftool.cpp \
   $$PWD/kcms/lookandfeel/lookandfeeldata.cpp \
   $$PWD/kcms/style/package/contents/ui/EffectSettingsPopup.qml \
   $$PWD/kcms/style/package/contents/ui/GtkStylePage.qml \
   $$PWD/kcms/style/package/contents/ui/main.qml \
   $$PWD/kcms/style/gtkpage.cpp \
   $$PWD/kcms/style/gtkthemesmodel.cpp \
   $$PWD/kcms/style/kcmstyle.cpp \
   $$PWD/kcms/style/previewitem.cpp \
   $$PWD/kcms/style/styleconfdialog.cpp \
   $$PWD/kcms/style/styledata.cpp \
   $$PWD/kcms/style/stylesmodel.cpp \
   $$PWD/kcms/translations/package/contents/ui/main.qml \
   $$PWD/kcms/translations/translations.cpp \
   $$PWD/kcms/translations/translationsmodel.cpp \
   $$PWD/kcms/translations/translationssettings.cpp \
   $$PWD/kioslave/applications/kio_applications.cpp \
   $$PWD/kioslave/desktop/tests/kio_desktop_test.cpp \
   $$PWD/kioslave/desktop/desktopnotifier.cpp \
   $$PWD/kioslave/desktop/kio_desktop.cpp \
   $$PWD/klipper/autotests/historymodeltest.cpp \
   $$PWD/klipper/autotests/historytest.cpp \
   $$PWD/klipper/systemclipboard/tests/paste.cpp \
   $$PWD/klipper/systemclipboard/qtclipboard.cpp \
   $$PWD/klipper/systemclipboard/systemclipboard.cpp \
   $$PWD/klipper/systemclipboard/waylandclipboard.cpp \
   $$PWD/klipper/actionstreewidget.cpp \
   $$PWD/klipper/clipboardengine.cpp \
   $$PWD/klipper/clipboardjob.cpp \
   $$PWD/klipper/clipboardservice.cpp \
   $$PWD/klipper/clipcommandprocess.cpp \
   $$PWD/klipper/configdialog.cpp \
   $$PWD/klipper/editactiondialog.cpp \
   $$PWD/klipper/history.cpp \
   $$PWD/klipper/historyimageitem.cpp \
   $$PWD/klipper/historyitem.cpp \
   $$PWD/klipper/historymodel.cpp \
   $$PWD/klipper/historystringitem.cpp \
   $$PWD/klipper/historyurlitem.cpp \
   $$PWD/klipper/klipper.cpp \
   $$PWD/klipper/klipperpopup.cpp \
   $$PWD/klipper/main.cpp \
   $$PWD/klipper/popupproxy.cpp \
   $$PWD/klipper/tray.cpp \
   $$PWD/klipper/urlgrabber.cpp \
   $$PWD/krunner/update/krunnerglobalshortcuts.cpp \
   $$PWD/krunner/update/krunnerplugins.cpp \
   $$PWD/krunner/main.cpp \
   $$PWD/krunner/view.cpp \
   $$PWD/ksmserver/tests/autostarttest.cpp \
   $$PWD/ksmserver/client.cpp \
   $$PWD/ksmserver/legacy.cpp \
   $$PWD/ksmserver/logout.cpp \
   $$PWD/ksmserver/main.cpp \
   $$PWD/ksmserver/server.cpp \
   $$PWD/ksplash/ksplashqml/themes/Classic/FadeIn.qml \
   $$PWD/ksplash/ksplashqml/themes/Classic/main.qml \
   $$PWD/ksplash/ksplashqml/themes/Minimalistic/main.qml \
   $$PWD/ksplash/ksplashqml/main.cpp \
   $$PWD/ksplash/ksplashqml/splashapp.cpp \
   $$PWD/ksplash/ksplashqml/splashwindow.cpp \
   $$PWD/ktimezoned/ktimezoned.cpp \
   $$PWD/ktimezoned/ktimezoned_win.cpp \
   $$PWD/libcolorcorrect/autotests/mock_kwin.cpp \
   $$PWD/libcolorcorrect/autotests/nightcolortest.cpp \
   $$PWD/libcolorcorrect/declarative/colorcorrectplugin.cpp \
   $$PWD/libcolorcorrect/kded/locationupdater.cpp \
   $$PWD/libcolorcorrect/compositorcoloradaptor.cpp \
   $$PWD/libcolorcorrect/geolocator.cpp \
   $$PWD/libcolorcorrect/suncalc.cpp \
   $$PWD/libdbusmenuqt/test/main.cpp \
   $$PWD/libdbusmenuqt/dbusmenuimporter.cpp \
   $$PWD/libdbusmenuqt/dbusmenushortcut_p.cpp \
   $$PWD/libdbusmenuqt/dbusmenutypes_p.cpp \
   $$PWD/libdbusmenuqt/utils.cpp \
   $$PWD/libkworkspace/autotests/testPlatformDetection.cpp \
   $$PWD/libkworkspace/tests/sessiontest.cpp \
   $$PWD/libkworkspace/tests/syncdbusenvtest.cpp \
   $$PWD/libkworkspace/kdisplaymanager.cpp \
   $$PWD/libkworkspace/kworkspace.cpp \
   $$PWD/libkworkspace/login1_manager_interface.cpp \
   $$PWD/libkworkspace/sessionmanagement.cpp \
   $$PWD/libkworkspace/sessionmanagementbackend.cpp \
   $$PWD/libkworkspace/updatelaunchenvjob.cpp \
   $$PWD/libnotificationmanager/autotests/notifications_test.cpp \
   $$PWD/libnotificationmanager/declarative/notificationmanagerplugin.cpp \
   $$PWD/libnotificationmanager/abstractnotificationsmodel.cpp \
   $$PWD/libnotificationmanager/job.cpp \
   $$PWD/libnotificationmanager/job_p.cpp \
   $$PWD/libnotificationmanager/jobsmodel.cpp \
   $$PWD/libnotificationmanager/jobsmodel_p.cpp \
   $$PWD/libnotificationmanager/limitedrowcountproxymodel.cpp \
   $$PWD/libnotificationmanager/mirroredscreenstracker.cpp \
   $$PWD/libnotificationmanager/notification.cpp \
   $$PWD/libnotificationmanager/notificationfilterproxymodel.cpp \
   $$PWD/libnotificationmanager/notificationgroupcollapsingproxymodel.cpp \
   $$PWD/libnotificationmanager/notificationgroupingproxymodel.cpp \
   $$PWD/libnotificationmanager/notifications.cpp \
   $$PWD/libnotificationmanager/notificationsmodel.cpp \
   $$PWD/libnotificationmanager/notificationsortproxymodel.cpp \
   $$PWD/libnotificationmanager/server.cpp \
   $$PWD/libnotificationmanager/server_p.cpp \
   $$PWD/libnotificationmanager/serverinfo.cpp \
   $$PWD/libnotificationmanager/settings.cpp \
   $$PWD/libnotificationmanager/utils.cpp \
   $$PWD/libnotificationmanager/watchednotificationsmodel.cpp \
   $$PWD/libtaskmanager/autotests/launchertasksmodeltest.cpp \
   $$PWD/libtaskmanager/autotests/tasktoolstest.cpp \
   $$PWD/libtaskmanager/declarative/pipewirecore.cpp \
   $$PWD/libtaskmanager/declarative/pipewiresourceitem.cpp \
   $$PWD/libtaskmanager/declarative/pipewiresourcestream.cpp \
   $$PWD/libtaskmanager/declarative/screencasting.cpp \
   $$PWD/libtaskmanager/declarative/screencastingrequest.cpp \
   $$PWD/libtaskmanager/declarative/taskmanagerplugin.cpp \
   $$PWD/libtaskmanager/abstracttasksmodel.cpp \
   $$PWD/libtaskmanager/abstracttasksproxymodeliface.cpp \
   $$PWD/libtaskmanager/abstractwindowtasksmodel.cpp \
   $$PWD/libtaskmanager/activityinfo.cpp \
   $$PWD/libtaskmanager/concatenatetasksproxymodel.cpp \
   $$PWD/libtaskmanager/flattentaskgroupsproxymodel.cpp \
   $$PWD/libtaskmanager/launchertasksmodel.cpp \
   $$PWD/libtaskmanager/startuptasksmodel.cpp \
   $$PWD/libtaskmanager/taskfilterproxymodel.cpp \
   $$PWD/libtaskmanager/taskgroupingproxymodel.cpp \
   $$PWD/libtaskmanager/tasksmodel.cpp \
   $$PWD/libtaskmanager/tasktools.cpp \
   $$PWD/libtaskmanager/virtualdesktopinfo.cpp \
   $$PWD/libtaskmanager/waylandtasksmodel.cpp \
   $$PWD/libtaskmanager/windowtasksmodel.cpp \
   $$PWD/libtaskmanager/xwindowsystemeventbatcher.cpp \
   $$PWD/libtaskmanager/xwindowtasksmodel.cpp \
   $$PWD/logout-greeter/tests/main.cpp \
   $$PWD/logout-greeter/greeter.cpp \
   $$PWD/logout-greeter/main.cpp \
   $$PWD/logout-greeter/shutdowndlg.cpp \
   $$PWD/lookandfeel/contents/components/ActionButton.qml \
   $$PWD/lookandfeel/contents/components/Battery.qml \
   $$PWD/lookandfeel/contents/components/Clock.qml \
   $$PWD/lookandfeel/contents/components/KeyboardLayoutButton.qml \
   $$PWD/lookandfeel/contents/components/SessionManagementScreen.qml \
   $$PWD/lookandfeel/contents/components/UserDelegate.qml \
   $$PWD/lookandfeel/contents/components/UserList.qml \
   $$PWD/lookandfeel/contents/components/VirtualKeyboard.qml \
   $$PWD/lookandfeel/contents/components/WallpaperFader.qml \
   $$PWD/lookandfeel/contents/desktopswitcher/DesktopSwitcher.qml \
   $$PWD/lookandfeel/contents/lockscreen/config.qml \
   $$PWD/lookandfeel/contents/lockscreen/LockOsd.qml \
   $$PWD/lookandfeel/contents/lockscreen/LockScreen.qml \
   $$PWD/lookandfeel/contents/lockscreen/LockScreenUi.qml \
   $$PWD/lookandfeel/contents/lockscreen/MainBlock.qml \
   $$PWD/lookandfeel/contents/lockscreen/MediaControls.qml \
   $$PWD/lookandfeel/contents/logout/dummydata/screenGeometry.qml \
   $$PWD/lookandfeel/contents/logout/Logout.qml \
   $$PWD/lookandfeel/contents/logout/LogoutButton.qml \
   $$PWD/lookandfeel/contents/osd/Osd.qml \
   $$PWD/lookandfeel/contents/osd/OsdItem.qml \
   $$PWD/lookandfeel/contents/runcommand/RunCommand.qml \
   $$PWD/lookandfeel/contents/splash/Splash.qml \
   $$PWD/lookandfeel/contents/windowdecoration/WindowDecoration.qml \
   $$PWD/lookandfeel/contents/windowswitcher/WindowSwitcher.qml \
   $$PWD/phonon/platform_kde/debug.cpp \
   $$PWD/phonon/platform_kde/kdeplatformplugin.cpp \
   $$PWD/phonon/platform_kde/kiomediastream.cpp \
   $$PWD/plasma-windowed/main.cpp \
   $$PWD/plasma-windowed/plasmawindowedcorona.cpp \
   $$PWD/plasma-windowed/plasmawindowedview.cpp \
   $$PWD/plasmacalendarintegration/qmlhelper/holidayeventshelperplugin.cpp \
   $$PWD/plasmacalendarintegration/HolidaysConfig.qml \
   $$PWD/plasmacalendarintegration/holidaysevents.cpp \
   $$PWD/runners/activities/activityrunner.cpp \
   $$PWD/runners/appstream/appstreamrunner.cpp \
   $$PWD/runners/baloo/baloosearchrunner.cpp \
   $$PWD/runners/bookmarks/browsers/chrome.cpp \
   $$PWD/runners/bookmarks/browsers/chromefindprofile.cpp \
   $$PWD/runners/bookmarks/browsers/falkon.cpp \
   $$PWD/runners/bookmarks/browsers/firefox.cpp \
   $$PWD/runners/bookmarks/browsers/kdebrowser.cpp \
   $$PWD/runners/bookmarks/browsers/opera.cpp \
   $$PWD/runners/bookmarks/tests/testchromebookmarks.cpp \
   $$PWD/runners/bookmarks/bookmarkmatch.cpp \
   $$PWD/runners/bookmarks/bookmarksrunner.cpp \
   $$PWD/runners/bookmarks/browserfactory.cpp \
   $$PWD/runners/bookmarks/favicon.cpp \
   $$PWD/runners/bookmarks/faviconfromblob.cpp \
   $$PWD/runners/bookmarks/fetchsqlite.cpp \
   $$PWD/runners/calculator/calculatorrunner.cpp \
   $$PWD/runners/calculator/qalculate_engine.cpp \
   $$PWD/runners/kill/killrunner.cpp \
   $$PWD/runners/kill/killrunner_config.cpp \
   $$PWD/runners/locations/locationrunner.cpp \
   $$PWD/runners/places/placesrunner.cpp \
   $$PWD/runners/powerdevil/PowerDevilRunner.cpp \
   $$PWD/runners/recentdocuments/recentdocuments.cpp \
   $$PWD/runners/services/autotests/servicerunnertest.cpp \
   $$PWD/runners/services/plugin.cpp \
   $$PWD/runners/services/servicerunner.cpp \
   $$PWD/runners/sessions/sessionrunner.cpp \
   $$PWD/runners/shell/shellrunner.cpp \
   $$PWD/runners/webshortcuts/webshortcutrunner.cpp \
   $$PWD/runners/windowedwidgets/windowedwidgetsrunner.cpp \
   $$PWD/runners/windows/windowsrunner.cpp \
   $$PWD/sddm-theme/components/ActionButton.qml \
   $$PWD/sddm-theme/components/Battery.qml \
   $$PWD/sddm-theme/components/Clock.qml \
   $$PWD/sddm-theme/components/KeyboardLayoutButton.qml \
   $$PWD/sddm-theme/components/SessionManagementScreen.qml \
   $$PWD/sddm-theme/components/UserDelegate.qml \
   $$PWD/sddm-theme/components/UserList.qml \
   $$PWD/sddm-theme/components/VirtualKeyboard.qml \
   $$PWD/sddm-theme/components/WallpaperFader.qml \
   $$PWD/sddm-theme/dummydata/config.qml \
   $$PWD/sddm-theme/dummydata/keyboard.qml \
   $$PWD/sddm-theme/dummydata/screenModel.qml \
   $$PWD/sddm-theme/dummydata/sddm.qml \
   $$PWD/sddm-theme/dummydata/sessionModel.qml \
   $$PWD/sddm-theme/dummydata/userModel.qml \
   $$PWD/sddm-theme/Background.qml \
   $$PWD/sddm-theme/BreezeMenuStyle.qml \
   $$PWD/sddm-theme/KeyboardButton.qml \
   $$PWD/sddm-theme/Login.qml \
   $$PWD/sddm-theme/Main.qml \
   $$PWD/sddm-theme/SessionButton.qml \
   $$PWD/shell/autotests/desktopview.cpp \
   $$PWD/shell/autotests/screenpooltest.cpp \
   $$PWD/shell/packageplugins/layouttemplate/layouttemplate.cpp \
   $$PWD/shell/packageplugins/lookandfeel/lookandfeel.cpp \
   $$PWD/shell/packageplugins/qmlWallpaper/wallpaper.cpp \
   $$PWD/shell/packageplugins/shell/shellpackage.cpp \
   $$PWD/shell/packageplugins/wallpaperimages/wallpaperpackage.cpp \
   $$PWD/shell/scripting/appinterface.cpp \
   $$PWD/shell/scripting/applet.cpp \
   $$PWD/shell/scripting/configgroup.cpp \
   $$PWD/shell/scripting/containment.cpp \
   $$PWD/shell/scripting/panel.cpp \
   $$PWD/shell/scripting/scriptengine.cpp \
   $$PWD/shell/scripting/scriptengine_v1.cpp \
   $$PWD/shell/scripting/widget.cpp \
   $$PWD/shell/alternativeshelper.cpp \
   $$PWD/shell/containmentconfigview.cpp \
   $$PWD/shell/coronatesthelper.cpp \
   $$PWD/shell/currentcontainmentactionsmodel.cpp \
   $$PWD/shell/desktopview.cpp \
   $$PWD/shell/main.cpp \
   $$PWD/shell/osd.cpp \
   $$PWD/shell/panelconfigview.cpp \
   $$PWD/shell/panelshadows.cpp \
   $$PWD/shell/panelview.cpp \
   $$PWD/shell/screenpool.cpp \
   $$PWD/shell/shellcorona.cpp \
   $$PWD/shell/softwarerendernotifier.cpp \
   $$PWD/shell/standaloneappcorona.cpp \
   $$PWD/shell/strutmanager.cpp \
   $$PWD/shell/userfeedback.cpp \
   $$PWD/solidautoeject/solidautoeject.cpp \
   $$PWD/soliduiserver/soliduiserver.cpp \
   $$PWD/startkde/kcheckrunning/kcheckrunning.cpp \
   $$PWD/startkde/kcminit/main.cpp \
   $$PWD/startkde/plasma-session/plasma-autostart-list/main.cpp \
   $$PWD/startkde/plasma-session/autostart.cpp \
   $$PWD/startkde/plasma-session/main.cpp \
   $$PWD/startkde/plasma-session/startup.cpp \
   $$PWD/startkde/plasma-shutdown/main.cpp \
   $$PWD/startkde/plasma-shutdown/shutdown.cpp \
   $$PWD/startkde/waitforname/main.cpp \
   $$PWD/startkde/waitforname/waiter.cpp \
   $$PWD/startkde/kde-systemd-start-condition.cpp \
   $$PWD/startkde/startplasma-wayland.cpp \
   $$PWD/startkde/startplasma-waylandsession.cpp \
   $$PWD/startkde/startplasma-x11.cpp \
   $$PWD/startkde/startplasma.cpp \
   $$PWD/statusnotifierwatcher/statusnotifierwatcher.cpp \
   $$PWD/systemmonitor/kdedksysguard.cpp \
   $$PWD/systemmonitor/ksystemactivitydialog.cpp \
   $$PWD/systemmonitor/main.cpp \
   $$PWD/templates/ion-dataengine/src/ion-%{APPNAMELC}.cpp \
   $$PWD/wallpapers/color/contents/ui/config.qml \
   $$PWD/wallpapers/color/contents/ui/main.qml \
   $$PWD/wallpapers/image/autotests/testfindpreferredimage.cpp \
   $$PWD/wallpapers/image/imagepackage/contents/ui/config.qml \
   $$PWD/wallpapers/image/imagepackage/contents/ui/main.qml \
   $$PWD/wallpapers/image/imagepackage/contents/ui/WallpaperDelegate.qml \
   $$PWD/wallpapers/image/imagepackage/platformcontents/phone/ui/config.qml \
   $$PWD/wallpapers/image/imagepackage/platformcontents/phone/ui/customwallpaper.qml \
   $$PWD/wallpapers/image/imagepackage/platformcontents/phone/ui/WallpaperDelegate.qml \
   $$PWD/wallpapers/image/imagepackage/platformcontents/touch/ui/config.qml \
   $$PWD/wallpapers/image/imagepackage/platformcontents/touch/ui/WallpaperDelegate.qml \
   $$PWD/wallpapers/image/backgroundlistmodel.cpp \
   $$PWD/wallpapers/image/image.cpp \
   $$PWD/wallpapers/image/imageplugin.cpp \
   $$PWD/wallpapers/image/slidefiltermodel.cpp \
   $$PWD/wallpapers/image/slidemodel.cpp \
   $$PWD/xembed-sni-proxy/fdoselectionmanager.cpp \
   $$PWD/xembed-sni-proxy/main.cpp \
   $$PWD/xembed-sni-proxy/snidbus.cpp \
   $$PWD/xembed-sni-proxy/sniproxy.cpp \
   $$PWD/xembed-sni-proxy/xtestsender.cpp \
   shell/gesturedispatcher.cpp \
   shell/globalgestureserver.cpp \
   shell/toast.cpp

INCLUDEPATH = \
    $$PWD/applets/appmenu/lib \
    $$PWD/applets/appmenu/plugin \
    $$PWD/applets/calendar \
    $$PWD/applets/digital-clock/plugin \
    $$PWD/applets/icon \
    $$PWD/applets/kicker/plugin \
    $$PWD/applets/notifications \
    $$PWD/applets/panelspacer/plugin \
    $$PWD/applets/systemmonitor/systemmonitor \
    $$PWD/applets/systemtray \
    $$PWD/applets/systemtray/container \
    $$PWD/applets/systemtray/tests/statusnotifier \
    $$PWD/appmenu \
    $$PWD/components/containmentlayoutmanager \
    $$PWD/components/keyboardlayout \
    $$PWD/components/sessionsprivate \
    $$PWD/components/shellprivate \
    $$PWD/components/shellprivate/interactiveconsole \
    $$PWD/components/shellprivate/wallpaperplugin \
    $$PWD/components/shellprivate/widgetexplorer \
    $$PWD/containmentactions/applauncher \
    $$PWD/containmentactions/contextmenu \
    $$PWD/containmentactions/paste \
    $$PWD/containmentactions/switchactivity \
    $$PWD/containmentactions/switchdesktop \
    $$PWD/containmentactions/switchwindow \
    $$PWD/dataengines/activities \
    $$PWD/dataengines/applicationjobs \
    $$PWD/dataengines/apps \
    $$PWD/dataengines/devicenotifications \
    $$PWD/dataengines/dict \
    $$PWD/dataengines/executable \
    $$PWD/dataengines/favicons \
    $$PWD/dataengines/filebrowser \
    $$PWD/dataengines/geolocation \
    $$PWD/dataengines/hotplug \
    $$PWD/dataengines/keystate \
    $$PWD/dataengines/mouse \
    $$PWD/dataengines/mpris2 \
    $$PWD/dataengines/notifications \
    $$PWD/dataengines/packagekit \
    $$PWD/dataengines/places \
    $$PWD/dataengines/powermanagement \
    $$PWD/dataengines/soliddevice \
    $$PWD/dataengines/statusnotifieritem \
    $$PWD/dataengines/systemmonitor \
    $$PWD/dataengines/time \
    $$PWD/dataengines/weather \
    $$PWD/dataengines/weather/ions \
    $$PWD/dataengines/weather/ions/bbcukmet \
    $$PWD/dataengines/weather/ions/envcan \
    $$PWD/dataengines/weather/ions/noaa \
    $$PWD/dataengines/weather/ions/wetter.com \
    $$PWD/freespacenotifier \
    $$PWD/gmenu-dbusmenu-proxy \
    $$PWD/kcms/colors \
    $$PWD/kcms/colors/editor \
    $$PWD/kcms/cursortheme \
    $$PWD/kcms/cursortheme/xcursor \
    $$PWD/kcms/desktoptheme \
    $$PWD/kcms/feedback \
    $$PWD/kcms/fonts \
    $$PWD/kcms/icons \
    $$PWD/kcms/kfontinst/apps \
    $$PWD/kcms/kfontinst/dbus \
    $$PWD/kcms/kfontinst/kcmfontinst \
    $$PWD/kcms/kfontinst/kio \
    $$PWD/kcms/kfontinst/lib \
    $$PWD/kcms/kfontinst/thumbnail \
    $$PWD/kcms/kfontinst/viewpart \
    $$PWD/kcms/krdb \
    $$PWD/kcms/lookandfeel \
    $$PWD/kcms/style \
    $$PWD/kcms/translations \
    $$PWD/kioslave/desktop \
    $$PWD/klipper \
    $$PWD/klipper/systemclipboard \
    $$PWD/krunner \
    $$PWD/ksmserver \
    $$PWD/ksplash/ksplashqml \
    $$PWD/ktimezoned \
    $$PWD/libcolorcorrect \
    $$PWD/libcolorcorrect/autotests \
    $$PWD/libcolorcorrect/declarative \
    $$PWD/libcolorcorrect/kded \
    $$PWD/libdbusmenuqt \
    $$PWD/libkworkspace \
    $$PWD/libnotificationmanager \
    $$PWD/libnotificationmanager/declarative \
    $$PWD/libtaskmanager \
    $$PWD/libtaskmanager/declarative \
    $$PWD/logout-greeter \
    $$PWD/phonon/platform_kde \
    $$PWD/plasma-windowed \
    $$PWD/plasmacalendarintegration \
    $$PWD/plasmacalendarintegration/qmlhelper \
    $$PWD/runners/activities \
    $$PWD/runners/appstream \
    $$PWD/runners/baloo \
    $$PWD/runners/bookmarks \
    $$PWD/runners/bookmarks/browsers \
    $$PWD/runners/bookmarks/tests \
    $$PWD/runners/calculator \
    $$PWD/runners/kill \
    $$PWD/runners/locations \
    $$PWD/runners/places \
    $$PWD/runners/powerdevil \
    $$PWD/runners/recentdocuments \
    $$PWD/runners/services \
    $$PWD/runners/sessions \
    $$PWD/runners/shell \
    $$PWD/runners/webshortcuts \
    $$PWD/runners/windowedwidgets \
    $$PWD/runners/windows \
    $$PWD/shell \
    $$PWD/shell/autotests \
    $$PWD/shell/packageplugins/layouttemplate \
    $$PWD/shell/packageplugins/lookandfeel \
    $$PWD/shell/packageplugins/qmlWallpaper \
    $$PWD/shell/packageplugins/shell \
    $$PWD/shell/packageplugins/wallpaperimages \
    $$PWD/shell/scripting \
    $$PWD/solidautoeject \
    $$PWD/soliduiserver \
    $$PWD/startkde \
    $$PWD/startkde/kcheckrunning \
    $$PWD/startkde/kcminit \
    $$PWD/startkde/plasma-session \
    $$PWD/startkde/plasma-shutdown \
    $$PWD/startkde/waitforname \
    $$PWD/statusnotifierwatcher \
    $$PWD/systemmonitor \
    $$PWD/templates/ion-dataengine/src \
    $$PWD/wallpapers/image \
    $$PWD/xembed-sni-proxy

#DEFINES = 

DISTFILES += \
    lookandfeel/contents/toast/Toast.qml \
    lookandfeel/contents/toast/ToastItem.qml

